# RGB Matrix Ticker Config V2

## General Settings

# Pixel Gap between icon and the text
iconGap: 6

# Pixel Gap between each stock/ crypto
priceGap: 10

# Amount of times the render queue should loop before re-querying the modules
moduleLoop: 5

# Brightness when the screen is awake
awakeBrightness: 75

# Brightness when the screen is asleep
sleepBrightness: 10 

# Hour of the day to start sleeping
sleepStart: 21

# Hour of the day to stop sleeping
sleepEnd: 6 

# Enable to change the display to a clock instead of normal ticker scrolling during sleep
sleepClock: True

# Display in full or half mode
displayMode: full

# Module scrolling speed (slow, normal and fast)
scrollSpeed: slow
topScrollSpeed: normal
bottomScrollSpeed: normal

topDisplayModules: [crypto]
bottomDisplayModules: []

## Modules

crypto:
  enabled: True
  fiat: aud  # Fiat currency to use. Compatible currenncies available at https://api.coingecko.com/api/v3/simple/supported_vs_currencies
  currencyPrefix: $ # Prefix to show before fiat (dollar, euro, etc.) Probably broken if you don't use $ or letters bcause of the fonts.
  symbols: # Coingecko Coin IDs
    - bitcoin
    - litecoin
    - ethereum
    - matic-network
    - ripple
    - tezos
    - solana